### ISSUE TITLE
Anti Virus problem

### ISSUE THREAD

**Issue by ubionexd** [hypherionmc/simple-rpc-editor#1]
My antivirus says this is a Malware. Is this true?

**Comment by hypherionmc** [comment]
My one pc also detected it, but it appears to be a false positive. This issue is on NeutralinoJS's side. Both are open source, so you are free to go through he code to check.

I suggest opening an issue on their github as well

**Comment by hypherionmc** [comment]
I no longer use this framework since 2.0.0. So I am marking this as resolved for now. If you still have issues with the new version, please let me know
