### ISSUE TITLE
[BUG]: cant save

### ISSUE THREAD

**Issue by FQQD** [hypherionmc/simple-rpc-editor#14]
### Operating System

Linux

### App Version

3.0.2

### Detailed Description

I cant save. the save button doesnt overwrite the file. when i go into the text editor off the programm it gives me nothing. 
![image](https://user-images.githubusercontent.com/96952506/181913912-8f0ba4c5-ff01-4e8f-8cff-6db40b457eeb.png)
the copy to clipboard button copies nothing.

### Reproducing the issue

- Download newest appimage
- marking it as executable
- selecting "run once" in appimagelauncher 
![image](https://user-images.githubusercontent.com/96952506/181913944-62e7fc4a-4325-417d-bfda-a8e919d7edaf.png)
- opening the config
- changing something in the program
- clicking the save button
- looking with a text editor
- same file as before

**Comment by hypherionmc** [comment]
Hi. Thanks for the report. I'll have to fire up a Linux VM to test this. I don't have a linux setup atm.

In the meantime, while running the app, press `CTRL + SHIFT + I` and see if you see any errors in the console (red text)

**Comment by FQQD** [comment]
this is what i get in the console when pressing the save button:
`editorFunctions.js:108 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Array.<anonymous> (editorFunctions.js:108)
    at Function.each (jquery.js:391)
    at Object.<anonymous> (editorFunctions.js:56)
    at Function.each (jquery.js:391)
    at Object.saveConfig (editorFunctions.js:52)
    at a.saveConfig (App.vue:469)
    at Nn (vue.runtime.esm.js:2988)
    at HTMLAnchorElement.n (vue.runtime.esm.js:1786)
    at HTMLAnchorElement.Da.o._wrapper (vue.runtime.esm.js:7405)`

**Comment by hypherionmc** [comment]
Thanks for that info. I see it's a bug introduced with the latest editor update. 

Are you using the newest version of the mod or one of the older versions?
