### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by elhertz** [hypherionmc/simple-rpc-editor#2]
WINDOWS_WHITESCREEN_FIX(RUN AS ADMIN).bat didn't work and i'm still getting a blank screen
Running on windows 10 pro 64 bits latest update

Edit: Added video

https://user-images.githubusercontent.com/13700335/131414290-60ccc48a-b1d4-4e54-b348-f66403532ba0.mp4

**Comment by hypherionmc** [comment]
Issue has been fixed in 2.0.0+
